<?php
namespace Wei\EventWork\Tests;

use Wei\EventWork\Db;
use Wei\EventWork\EventLog;
use Wei\EventWork\EventSend;

/**
 * 测试发送事件
 * Class EventSendTest
 * @package Wei\EventWork\Tests
 */
class EventSendTest extends WeiTestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        Db::getDelete()->from(EventLog::TABLE_NAME)
            ->condition('data', '%EventSend%', 'like')
            ->delete();
    }

    /**
     * 测试发送事件
     */
    public function testSend()
    {
        EventSend::send('app_create', "EventSend");
        EventSend::send('app_create', "EventSend");
        $count = Db::getSelect()->from(EventLog::TABLE_NAME)->condition('data', '%EventSend%', 'like')->findCount();
        $this->assertEquals('2', $count);
    }

}