<?php
namespace Wei\EventWork\Tests;


use Composer\Autoload\ClassLoader;

use Wei\EventWork\Db;
use Wei\EventWork\EventModule;

/**
 * 测试事件模块类
 *
 * Class EventModuleTest
 * @package Wei\EventWork\Tests
 */
class EventModuleTest extends WeiTestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        Db::getDelete()->from(EventModule::TABLE_NAME)
            ->condition('module', 1)
            ->condition('event', 2)->delete();
    }

    /**
     * 测试创建
     */
    public function testCreate()
    {
        $obj = new EventModule();
        $id = $obj->create(1, 2);
        $bool = $id > 0 ? true: false;
        $this->assertTrue($id > 0 ? true: false);
    }

    /**
     * 获取模块记录
     */
    public function testGetByModuleType()
    {
        $obj = new EventModule();
        $result = $obj->getByModuleType(1, 2);
//        $this->assertEquals('', $result['error_ids']);
        $this->assertEquals('1', $result['module']);
        $this->assertEquals('2', $result['event']);
    }

    /**
     * 模块模块记录
     */
    public function testGetModule()
    {
        $obj = new EventModule();
        $result = $obj->getModule(1, 2);
        $this->assertEquals(array(), $result['event_ids']);
        $this->assertEquals('1', $result['module']);
        $this->assertEquals('2', $result['event']);
    }
}