<?php
namespace Wei\EventWork\Tests;

use Noodlehaus\Config;
use Wei\BriefDB\Common\Composer;

/**
 * 测试读取yml配置
 * Class YmlTest
 * @package Wei\EventWork\Tests
 */
class YmlTest extends WeiTestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * 测试读取配置文件
     */
    public function test()
    {
        // Load a single file
        $conf = Config::load(Composer::getComposerVendorDir().'/config/event.conf.yml');
        $eventLists = $conf->get('event_lists');
//        $this->assertEquals($eventLists['app_create'], 1);

        $moduleLists = $conf->get('module_lists');
//        $this->assertEquals($moduleLists['docker_module']['class'], 'DockerCustomer');
    }
}